Fixed bug in json file
Finally fixed the following error:
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
This was actually caused by the save function of the FileStorage class. I
failed to add the ".items" to the "self.__objects" statement. Als,
deleted some expressions and statements as I worked on fixing the bug.